name: linux
on: [push, pull_request]
jobs:
  build-Linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add - || exit 1
    - run: sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main" || exit 1
    - run: sudo apt-get update || exit 1
    - run: sudo apt-get install -y clang-10 libc++-10-dev libc++abi-10-dev shunit2 make || exit 1
    - run: export CC="clang-10" && export CXX="clang++-10" && ./build.sh
    - run: sudo make install
    - run: make distclean
